stages:
  - build

build_linux:
  image: archlinux:latest
  stage: build
  before_script:
    - pacman -Sy --noconfirm base-devel tar make clang raylib
    - pacman -S --noconfirm --needed mesa libx11 libxrandr libxi libxcursor libxinerama
  script:
    - make -B
  artifacts:
    name: "linux-build"
    paths:
      - app

build_windows:
  image: archlinux:latest
  stage: build
  before_script:
    - pacman -Sy --noconfirm base-devel mingw-w64-gcc curl unzip make
    - curl -LO https://github.com/raysan5/raylib/releases/download/5.5/raylib-5.5_win64_mingw-w64.zip
    - unzip raylib-5.5_win64_mingw-w64.zip 
    - mkdir -p lib
    - cp raylib-5.5_win64_mingw-w64/lib/raylib.dll ./lib/raylib.dll
    - rm -rf raylib-5.5_win64_mingw-w64
  script:
    - TARGET=windows make -B
  artifacts:
    name: "windows-build"
    paths:
      - "*.exe"
      - lib/raylib.dll
